[[plugins]]
  package = 'netlify-plugin-algolia-index'
    # all inputs is optional, we just show you the defaults below
    # [plugins.inputs]
      # exclude = ['about'] # don't index this file
      # indexName = searchIndex
